/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chenjun.struts.action;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chenjun.struts.form.FundreportForm;
import com.chenjun.utils.compress.Compress;

/**
 * MyEclipse Struts Creation date: 03-28-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/fundreport" name="fundreportForm"
 *                input="/fundreportTestJsp.jsp" scope="request" validate="true"
 */
public class FundreportAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FundreportForm fundreportForm = (FundreportForm) form;

		String date = fundreportForm.getDate();

		String reportDate = (String) request.getSession().getServletContext()
				.getAttribute("date");

		OutputStream os = null;
		try {
			os = response.getOutputStream();

			if (date == null || !reportDate.equals(date)) {
				byte flagByte = Compress.FLAG_UTF8_STRING_COMPRESSED_BYTEARRAY;

				os.write(flagByte);
				os.write(Compress.byteCompress((byte[]) request.getSession().getServletContext()
						.getAttribute("reportBytes")));
				os.flush();
			}

			else if (reportDate.equals(date)) {
				byte flagByte = Compress.FLAG_NO_UPDATE_INFO;

				os.write(flagByte);
				os.flush();
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				os.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return null;
	}
}