/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chenjun.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-10-2012
 * 
 * XDoclet definition:
 * @struts.form name="jjBaseInfoForm"
 */
public class JjBaseInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** dms property */
	private String dms;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the dms.
	 * @return String
	 */
	public String getDms() {
		return dms;
	}

	/** 
	 * Set the dms.
	 * @param dms The dms to set
	 */
	public void setDms(String dms) {
		this.dms = dms;
	}
}