/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chenjun.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2012
 * 
 * XDoclet definition:
 * @struts.form name="jjcfForm"
 */
public class JjcfForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** dm property */
	private String dm;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the dm.
	 * @return String
	 */
	public String getDm() {
		return dm;
	}

	/** 
	 * Set the dm.
	 * @param dm The dm to set
	 */
	public void setDm(String dm) {
		this.dm = dm;
	}
}