/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chenjun.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-10-2012
 * 
 * XDoclet definition:
 * @struts.form name="searchForm"
 */
public class SearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** info property */
	private String info;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the info.
	 * @return String
	 */
	public String getInfo() {
		return info;
	}

	/** 
	 * Set the info.
	 * @param info The info to set
	 */
	public void setInfo(String info) {
		this.info = info;
	}
}